name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - run: |
          wget https://github.com/buttercrab/mdBook/releases/download/v0.4.1-1/mdbook-0.4.1-1-linux-x86-64.tar.gz
          /bin/tar -zxvf mdbook-0.4.1-1-linux-x86-64.tar.gz
          ./mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
          cname: iamcoder.wiki
