name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - run: |
          curl -s https://api.github.com/repos/buttercrab/mdBook/releases/latest \
          | grep browser_download_url \
          | grep linux \
          | cut -d '"' -f 4 \
          | wget -qi -
          /bin/tar -zxvf mdbook-x86_64-unknown-linux-gnu.tar.gz
          ./mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
          cname: iamcoder.wiki
