name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: |
          curl -s https://api.github.com/repos/buttercrab/wiki-generator/releases/latest \
          | grep browser_download_url \
          | grep linux \
          | cut -d '"' -f 4 \
          | wget -qi -
          /bin/tar -zxvf wiki-generator-linux.tar.gz
          ./wiki-generator build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: iamcoder.wiki
